const ENGLISH_SECTION_TITLES: Record<string, string> = {
  "orientation": "Orientation",
  "prerequisite map": "Prerequisite Map",
  "core concept map": "Core Concept Map",
  "concept explanations": "Concept Explanations",
  "relationships and tradeoffs": "Relationships and Tradeoffs",
  "examples": "Examples",
  "common misconceptions": "Common Misconceptions",
  "retrieval questions": "Retrieval Questions",
  "next steps": "Next Steps",
  "core quantities and models": "Core Quantities and Models",
  "symbols, units, and dimensions": "Symbols, Units, and Dimensions",
  "formula intuition": "Formula Intuition",
  "assumptions and regimes": "Assumptions and Regimes",
  "worked examples": "Worked Examples",
  "edge cases and limiting cases": "Edge Cases and Limiting Cases",
  "common mistakes": "Common Mistakes",
  "minimal working workflow": "Minimal Working Workflow",
  "prerequisite tools and setup": "Prerequisite Tools and Setup",
  "core tasks": "Core Tasks",
  "step-by-step workflows": "Step-by-Step Workflows",
  "verification checklist": "Verification Checklist",
  "common mistakes and troubleshooting": "Common Mistakes and Troubleshooting",
  "practice tasks": "Practice Tasks",
  "hypothesis": "Hypothesis",
  "data and assumptions": "Data and Assumptions",
  "evaluation pipeline": "Evaluation Pipeline",
  "metrics": "Metrics",
  "baseline comparison": "Baseline Comparison",
  "bias and leakage risks": "Bias and Leakage Risks",
  "robustness checks": "Robustness Checks",
  "failure modes": "Failure Modes",
  "materials and tools": "Materials and Tools",
  "style or quality standards": "Style or Quality Standards",
  "core techniques": "Core Techniques",
  "process": "Process",
  "representative cases": "Representative Cases",
  "sensory or output standards": "Sensory or Output Standards",
  "common failures and fixes": "Common Failures and Fixes",
  "timeline": "Timeline",
  "key actors, works, or institutions": "Key Actors, Works, or Institutions",
  "causal forces": "Causal Forces",
  "major transitions": "Major Transitions",
  "conflicts or debates": "Conflicts or Debates",
  "legacy and modern relevance": "Legacy and Modern Relevance",
  "definition and intuition": "Definition and Intuition",
  "why it exists": "Why It Exists",
  "problem it solves": "Problem It Solves",
  "prerequisites": "Prerequisites",
  "concrete example": "Concrete Example",
  "relationship to neighboring concepts": "Relationship to Neighboring Concepts",
  "common misconception": "Common Misconception",
  "definition": "Definition",
  "intuition": "Intuition",
  "symbols and units": "Symbols and Units",
  "assumptions": "Assumptions",
  "when the model applies": "When the Model Applies",
  "simple numerical example": "Simple Numerical Example",
  "what breaks when assumptions fail": "What Breaks When Assumptions Fail",
  "goal": "Goal",
  "when to use it": "When to Use It",
  "steps": "Steps",
  "menu path or shortcut if applicable": "Menu Path or Shortcut If Applicable",
  "expected result": "Expected Result",
  "how to verify the output": "How to Verify the Output",
  "what it measures": "What It Measures",
  "why it matters": "Why It Matters",
  "how to compute or test it": "How to Compute or Test It",
  "how it fails": "How It Fails",
  "example": "Example",
  "diagnostic check": "Diagnostic Check",
  "purpose": "Purpose",
  "materials or conditions": "Materials or Conditions",
  "sensory or quality standard": "Sensory or Quality Standard",
  "common failure": "Common Failure",
  "fix": "Fix",
  "period or transition": "Period or Transition",
  "what changed": "What Changed",
  "why it changed": "Why It Changed",
  "key actors or examples": "Key Actors or Examples",
  "broader context": "Broader Context",
  "modern relevance": "Modern Relevance",
};

const LOCALIZED_SECTION_TITLES: Record<string, Record<string, string>> = {
  zh: {
    "orientation": "学习定位",
    "prerequisite map": "前置知识地图",
    "core concept map": "核心概念地图",
    "concept explanations": "概念解释",
    "relationships and tradeoffs": "关系与取舍",
    "examples": "例子",
    "common misconceptions": "常见误解",
    "retrieval questions": "自我检索问题",
    "next steps": "后续学习",
    "core quantities and models": "核心量与模型",
    "symbols, units, and dimensions": "符号、单位与量纲",
    "formula intuition": "公式直觉",
    "assumptions and regimes": "假设与适用区间",
    "worked examples": "演算例子",
    "edge cases and limiting cases": "边界情况与极限情况",
    "common mistakes": "常见错误",
    "minimal working workflow": "最小可用流程",
    "prerequisite tools and setup": "前置工具与设置",
    "core tasks": "核心任务",
    "step-by-step workflows": "分步工作流",
    "verification checklist": "验证清单",
    "common mistakes and troubleshooting": "常见错误与排查",
    "practice tasks": "练习任务",
    "hypothesis": "假设",
    "data and assumptions": "数据与假设",
    "evaluation pipeline": "评估流程",
    "metrics": "指标",
    "baseline comparison": "基线比较",
    "bias and leakage risks": "偏差与泄漏风险",
    "robustness checks": "稳健性检查",
    "failure modes": "失败模式",
    "materials and tools": "材料与工具",
    "style or quality standards": "风格或质量标准",
    "core techniques": "核心技法",
    "process": "过程",
    "representative cases": "代表性案例",
    "sensory or output standards": "感官或输出标准",
    "common failures and fixes": "常见失败与修正",
    "timeline": "时间线",
    "key actors, works, or institutions": "关键人物、作品或机构",
    "causal forces": "因果力量",
    "major transitions": "主要转变",
    "conflicts or debates": "冲突或争论",
    "legacy and modern relevance": "遗产与当代关联",
    "definition and intuition": "定义与直觉",
    "why it exists": "为什么存在",
    "problem it solves": "解决的问题",
    "prerequisites": "前置知识",
    "concrete example": "具体例子",
    "relationship to neighboring concepts": "与相邻概念的关系",
    "common misconception": "常见误解",
    "definition": "定义",
    "intuition": "直觉",
    "symbols and units": "符号与单位",
    "assumptions": "假设",
    "when the model applies": "模型适用条件",
    "simple numerical example": "简单数值例子",
    "what breaks when assumptions fail": "假设失效时会出什么问题",
    "goal": "目标",
    "when to use it": "何时使用",
    "steps": "步骤",
    "menu path or shortcut if applicable": "菜单路径或快捷键",
    "expected result": "预期结果",
    "how to verify the output": "如何验证输出",
    "what it measures": "衡量什么",
    "why it matters": "为什么重要",
    "how to compute or test it": "如何计算或测试",
    "how it fails": "如何失效",
    "example": "例子",
    "diagnostic check": "诊断检查",
    "purpose": "目的",
    "materials or conditions": "材料或条件",
    "sensory or quality standard": "感官或质量标准",
    "common failure": "常见失败",
    "fix": "修正",
    "period or transition": "时期或转变",
    "what changed": "发生了什么变化",
    "why it changed": "为什么变化",
    "key actors or examples": "关键人物或例子",
    "broader context": "更广背景",
    "modern relevance": "当代关联",
  },
  zh_tw: {
    "orientation": "學習定位",
    "prerequisite map": "前置知識地圖",
    "core concept map": "核心概念地圖",
    "concept explanations": "概念解釋",
    "relationships and tradeoffs": "關係與取捨",
    "examples": "例子",
    "common misconceptions": "常見誤解",
    "retrieval questions": "自我檢索問題",
    "next steps": "後續學習",
    "core quantities and models": "核心量與模型",
    "symbols, units, and dimensions": "符號、單位與量綱",
    "formula intuition": "公式直覺",
    "assumptions and regimes": "假設與適用區間",
    "worked examples": "演算例子",
    "edge cases and limiting cases": "邊界情況與極限情況",
    "common mistakes": "常見錯誤",
    "minimal working workflow": "最小可用流程",
    "prerequisite tools and setup": "前置工具與設定",
    "core tasks": "核心任務",
    "step-by-step workflows": "分步工作流",
    "verification checklist": "驗證清單",
    "common mistakes and troubleshooting": "常見錯誤與排查",
    "practice tasks": "練習任務",
    "hypothesis": "假設",
    "data and assumptions": "資料與假設",
    "evaluation pipeline": "評估流程",
    "metrics": "指標",
    "baseline comparison": "基線比較",
    "bias and leakage risks": "偏差與洩漏風險",
    "robustness checks": "穩健性檢查",
    "failure modes": "失敗模式",
    "materials and tools": "材料與工具",
    "style or quality standards": "風格或品質標準",
    "core techniques": "核心技法",
    "process": "過程",
    "representative cases": "代表性案例",
    "sensory or output standards": "感官或輸出標準",
    "common failures and fixes": "常見失敗與修正",
    "timeline": "時間線",
    "key actors, works, or institutions": "關鍵人物、作品或機構",
    "causal forces": "因果力量",
    "major transitions": "主要轉變",
    "conflicts or debates": "衝突或爭論",
    "legacy and modern relevance": "遺產與當代關聯",
    "definition and intuition": "定義與直覺",
    "why it exists": "為什麼存在",
    "problem it solves": "解決的問題",
    "prerequisites": "前置知識",
    "concrete example": "具體例子",
    "relationship to neighboring concepts": "與相鄰概念的關係",
    "common misconception": "常見誤解",
    "definition": "定義",
    "intuition": "直覺",
    "symbols and units": "符號與單位",
    "assumptions": "假設",
    "when the model applies": "模型適用條件",
    "simple numerical example": "簡單數值例子",
    "what breaks when assumptions fail": "假設失效時會出什麼問題",
    "goal": "目標",
    "when to use it": "何時使用",
    "steps": "步驟",
    "menu path or shortcut if applicable": "選單路徑或快捷鍵",
    "expected result": "預期結果",
    "how to verify the output": "如何驗證輸出",
    "what it measures": "衡量什麼",
    "why it matters": "為什麼重要",
    "how to compute or test it": "如何計算或測試",
    "how it fails": "如何失效",
    "example": "例子",
    "diagnostic check": "診斷檢查",
    "purpose": "目的",
    "materials or conditions": "材料或條件",
    "sensory or quality standard": "感官或品質標準",
    "common failure": "常見失敗",
    "fix": "修正",
    "period or transition": "時期或轉變",
    "what changed": "發生了什麼變化",
    "why it changed": "為什麼變化",
    "key actors or examples": "關鍵人物或例子",
    "broader context": "更廣背景",
    "modern relevance": "當代關聯",
  },
  ja: {
    "orientation": "学習の位置づけ",
    "prerequisite map": "前提知識マップ",
    "core concept map": "中核概念マップ",
    "concept explanations": "概念の説明",
    "relationships and tradeoffs": "関係とトレードオフ",
    "examples": "例",
    "common misconceptions": "よくある誤解",
    "retrieval questions": "想起練習の質問",
    "next steps": "次の学習",
    "core quantities and models": "中核となる量とモデル",
    "symbols, units, and dimensions": "記号、単位、次元",
    "formula intuition": "数式の直感",
    "assumptions and regimes": "仮定と適用領域",
    "worked examples": "解法例",
    "edge cases and limiting cases": "端点ケースと極限ケース",
    "common mistakes": "よくある間違い",
    "minimal working workflow": "最小実用ワークフロー",
    "prerequisite tools and setup": "前提ツールと設定",
    "core tasks": "中核タスク",
    "step-by-step workflows": "段階的ワークフロー",
    "verification checklist": "検証チェックリスト",
    "common mistakes and troubleshooting": "よくある間違いとトラブルシューティング",
    "practice tasks": "練習タスク",
    "hypothesis": "仮説",
    "data and assumptions": "データと仮定",
    "evaluation pipeline": "評価パイプライン",
    "metrics": "指標",
    "baseline comparison": "ベースライン比較",
    "bias and leakage risks": "バイアスと漏洩リスク",
    "robustness checks": "頑健性チェック",
    "failure modes": "失敗モード",
    "materials and tools": "材料と道具",
    "style or quality standards": "スタイルまたは品質基準",
    "core techniques": "中核技法",
    "process": "工程",
    "representative cases": "代表例",
    "sensory or output standards": "感覚または出力の基準",
    "common failures and fixes": "よくある失敗と修正",
    "timeline": "年表",
    "key actors, works, or institutions": "主要人物、作品、制度",
    "causal forces": "因果要因",
    "major transitions": "主要な転換",
    "conflicts or debates": "対立または論争",
    "legacy and modern relevance": "遺産と現代的意義",
  },
  ko: {
    "orientation": "학습 위치 잡기",
    "prerequisite map": "선수 지식 지도",
    "core concept map": "핵심 개념 지도",
    "concept explanations": "개념 설명",
    "relationships and tradeoffs": "관계와 트레이드오프",
    "examples": "예시",
    "common misconceptions": "흔한 오해",
    "retrieval questions": "인출 연습 질문",
    "next steps": "다음 학습",
    "core quantities and models": "핵심 수량과 모델",
    "symbols, units, and dimensions": "기호, 단위, 차원",
    "formula intuition": "공식의 직관",
    "assumptions and regimes": "가정과 적용 영역",
    "worked examples": "풀이 예제",
    "edge cases and limiting cases": "경계 사례와 극한 사례",
    "common mistakes": "흔한 실수",
    "minimal working workflow": "최소 실행 워크플로",
    "prerequisite tools and setup": "필수 도구와 설정",
    "core tasks": "핵심 작업",
    "step-by-step workflows": "단계별 워크플로",
    "verification checklist": "검증 체크리스트",
    "common mistakes and troubleshooting": "흔한 실수와 문제 해결",
    "practice tasks": "연습 과제",
    "hypothesis": "가설",
    "data and assumptions": "데이터와 가정",
    "evaluation pipeline": "평가 파이프라인",
    "metrics": "지표",
    "baseline comparison": "기준선 비교",
    "bias and leakage risks": "편향과 누수 위험",
    "robustness checks": "강건성 점검",
    "failure modes": "실패 모드",
    "materials and tools": "재료와 도구",
    "style or quality standards": "스타일 또는 품질 기준",
    "core techniques": "핵심 기법",
    "process": "과정",
    "representative cases": "대표 사례",
    "sensory or output standards": "감각 또는 출력 기준",
    "common failures and fixes": "흔한 실패와 수정",
    "timeline": "연표",
    "key actors, works, or institutions": "주요 인물, 작품, 기관",
    "causal forces": "인과 요인",
    "major transitions": "주요 전환",
    "conflicts or debates": "갈등 또는 논쟁",
    "legacy and modern relevance": "유산과 현대적 관련성",
  },
  vi: {
    "orientation": "Định hướng học tập",
    "prerequisite map": "Bản đồ kiến thức tiên quyết",
    "core concept map": "Bản đồ khái niệm cốt lõi",
    "concept explanations": "Giải thích khái niệm",
    "relationships and tradeoffs": "Quan hệ và đánh đổi",
    "examples": "Ví dụ",
    "common misconceptions": "Hiểu lầm thường gặp",
    "retrieval questions": "Câu hỏi gợi nhớ",
    "next steps": "Bước học tiếp theo",
    "core quantities and models": "Đại lượng và mô hình cốt lõi",
    "symbols, units, and dimensions": "Ký hiệu, đơn vị và thứ nguyên",
    "formula intuition": "Trực giác công thức",
    "assumptions and regimes": "Giả định và phạm vi áp dụng",
    "worked examples": "Ví dụ có lời giải",
    "edge cases and limiting cases": "Trường hợp biên và giới hạn",
    "common mistakes": "Lỗi thường gặp",
    "minimal working workflow": "Quy trình tối thiểu dùng được",
    "prerequisite tools and setup": "Công cụ và thiết lập tiên quyết",
    "core tasks": "Nhiệm vụ cốt lõi",
    "step-by-step workflows": "Quy trình từng bước",
    "verification checklist": "Danh sách kiểm tra xác minh",
    "common mistakes and troubleshooting": "Lỗi thường gặp và xử lý sự cố",
    "practice tasks": "Bài tập thực hành",
    "hypothesis": "Giả thuyết",
    "data and assumptions": "Dữ liệu và giả định",
    "evaluation pipeline": "Quy trình đánh giá",
    "metrics": "Chỉ số",
    "baseline comparison": "So sánh với đường cơ sở",
    "bias and leakage risks": "Rủi ro thiên lệch và rò rỉ",
    "robustness checks": "Kiểm tra độ vững",
    "failure modes": "Kiểu thất bại",
    "materials and tools": "Vật liệu và công cụ",
    "style or quality standards": "Chuẩn phong cách hoặc chất lượng",
    "core techniques": "Kỹ thuật cốt lõi",
    "process": "Quy trình",
    "representative cases": "Trường hợp tiêu biểu",
    "sensory or output standards": "Chuẩn cảm quan hoặc đầu ra",
    "common failures and fixes": "Lỗi thường gặp và cách sửa",
    "timeline": "Dòng thời gian",
    "key actors, works, or institutions": "Nhân vật, tác phẩm hoặc thể chế chủ chốt",
    "causal forces": "Lực nhân quả",
    "major transitions": "Chuyển đổi lớn",
    "conflicts or debates": "Xung đột hoặc tranh luận",
    "legacy and modern relevance": "Di sản và ý nghĩa hiện đại",
  },
  th: {
    "orientation": "กรอบการเรียนรู้",
    "prerequisite map": "แผนที่ความรู้พื้นฐาน",
    "core concept map": "แผนที่แนวคิดหลัก",
    "concept explanations": "คำอธิบายแนวคิด",
    "relationships and tradeoffs": "ความสัมพันธ์และการแลกเปลี่ยน",
    "examples": "ตัวอย่าง",
    "common misconceptions": "ความเข้าใจผิดที่พบบ่อย",
    "retrieval questions": "คำถามทบทวนจากความจำ",
    "next steps": "ขั้นตอนถัดไป",
    "core quantities and models": "ปริมาณและแบบจำลองหลัก",
    "symbols, units, and dimensions": "สัญลักษณ์ หน่วย และมิติ",
    "formula intuition": "สัญชาตญาณของสูตร",
    "assumptions and regimes": "สมมติฐานและขอบเขตการใช้",
    "worked examples": "ตัวอย่างพร้อมวิธีทำ",
    "edge cases and limiting cases": "กรณีขอบและกรณีจำกัด",
    "common mistakes": "ข้อผิดพลาดที่พบบ่อย",
    "minimal working workflow": "เวิร์กโฟลว์ขั้นต่ำที่ใช้งานได้",
    "prerequisite tools and setup": "เครื่องมือและการตั้งค่าที่ต้องมี",
    "core tasks": "งานหลัก",
    "step-by-step workflows": "เวิร์กโฟลว์ทีละขั้น",
    "verification checklist": "รายการตรวจสอบ",
    "common mistakes and troubleshooting": "ข้อผิดพลาดที่พบบ่อยและการแก้ปัญหา",
    "practice tasks": "งานฝึกปฏิบัติ",
    "hypothesis": "สมมติฐาน",
    "data and assumptions": "ข้อมูลและสมมติฐาน",
    "evaluation pipeline": "กระบวนการประเมิน",
    "metrics": "ตัวชี้วัด",
    "baseline comparison": "การเปรียบเทียบกับฐานอ้างอิง",
    "bias and leakage risks": "ความเสี่ยงจากอคติและการรั่วไหล",
    "robustness checks": "การตรวจสอบความทนทาน",
    "failure modes": "รูปแบบความล้มเหลว",
    "materials and tools": "วัสดุและเครื่องมือ",
    "style or quality standards": "มาตรฐานสไตล์หรือคุณภาพ",
    "core techniques": "เทคนิคหลัก",
    "process": "กระบวนการ",
    "representative cases": "กรณีตัวแทน",
    "sensory or output standards": "มาตรฐานทางประสาทสัมผัสหรือผลลัพธ์",
    "common failures and fixes": "ความล้มเหลวที่พบบ่อยและวิธีแก้",
    "timeline": "เส้นเวลา",
    "key actors, works, or institutions": "บุคคล ผลงาน หรือสถาบันสำคัญ",
    "causal forces": "ปัจจัยเชิงสาเหตุ",
    "major transitions": "การเปลี่ยนผ่านหลัก",
    "conflicts or debates": "ความขัดแย้งหรือข้อถกเถียง",
    "legacy and modern relevance": "มรดกและความเกี่ยวข้องในปัจจุบัน",
  },
  id: {
    "orientation": "Orientasi Belajar",
    "prerequisite map": "Peta Prasyarat",
    "core concept map": "Peta Konsep Inti",
    "concept explanations": "Penjelasan Konsep",
    "relationships and tradeoffs": "Relasi dan Trade-off",
    "examples": "Contoh",
    "common misconceptions": "Kesalahpahaman Umum",
    "retrieval questions": "Pertanyaan Ingatan",
    "next steps": "Langkah Berikutnya",
    "core quantities and models": "Besaran dan Model Inti",
    "symbols, units, and dimensions": "Simbol, Satuan, dan Dimensi",
    "formula intuition": "Intuisi Rumus",
    "assumptions and regimes": "Asumsi dan Rezim Penerapan",
    "worked examples": "Contoh Terhitung",
    "edge cases and limiting cases": "Kasus Tepi dan Kasus Batas",
    "common mistakes": "Kesalahan Umum",
    "minimal working workflow": "Alur Kerja Minimum yang Berfungsi",
    "prerequisite tools and setup": "Alat dan Pengaturan Prasyarat",
    "core tasks": "Tugas Inti",
    "step-by-step workflows": "Alur Kerja Langkah demi Langkah",
    "verification checklist": "Daftar Periksa Verifikasi",
    "common mistakes and troubleshooting": "Kesalahan Umum dan Pemecahan Masalah",
    "practice tasks": "Tugas Latihan",
    "hypothesis": "Hipotesis",
    "data and assumptions": "Data dan Asumsi",
    "evaluation pipeline": "Alur Evaluasi",
    "metrics": "Metrik",
    "baseline comparison": "Perbandingan Baseline",
    "bias and leakage risks": "Risiko Bias dan Kebocoran",
    "robustness checks": "Pemeriksaan Robustness",
    "failure modes": "Mode Kegagalan",
    "materials and tools": "Bahan dan Alat",
    "style or quality standards": "Standar Gaya atau Kualitas",
    "core techniques": "Teknik Inti",
    "process": "Proses",
    "representative cases": "Kasus Representatif",
    "sensory or output standards": "Standar Sensorik atau Output",
    "common failures and fixes": "Kegagalan Umum dan Perbaikan",
    "timeline": "Linimasa",
    "key actors, works, or institutions": "Aktor, Karya, atau Institusi Kunci",
    "causal forces": "Kekuatan Kausal",
    "major transitions": "Transisi Besar",
    "conflicts or debates": "Konflik atau Perdebatan",
    "legacy and modern relevance": "Warisan dan Relevansi Modern",
  },
  ms: {
    "orientation": "Orientasi Pembelajaran",
    "prerequisite map": "Peta Prasyarat",
    "core concept map": "Peta Konsep Teras",
    "concept explanations": "Penjelasan Konsep",
    "relationships and tradeoffs": "Hubungan dan Tukar Ganti",
    "examples": "Contoh",
    "common misconceptions": "Salah Faham Lazim",
    "retrieval questions": "Soalan Ingatan Semula",
    "next steps": "Langkah Seterusnya",
    "core quantities and models": "Kuantiti dan Model Teras",
    "symbols, units, and dimensions": "Simbol, Unit, dan Dimensi",
    "formula intuition": "Intuisi Formula",
    "assumptions and regimes": "Andaian dan Rejim Aplikasi",
    "worked examples": "Contoh Berjawapan",
    "edge cases and limiting cases": "Kes Pinggir dan Kes Had",
    "common mistakes": "Kesilapan Lazim",
    "minimal working workflow": "Aliran Kerja Minimum yang Berfungsi",
    "prerequisite tools and setup": "Alat dan Tetapan Prasyarat",
    "core tasks": "Tugas Teras",
    "step-by-step workflows": "Aliran Kerja Langkah demi Langkah",
    "verification checklist": "Senarai Semak Pengesahan",
    "common mistakes and troubleshooting": "Kesilapan Lazim dan Penyelesaian Masalah",
    "practice tasks": "Tugas Latihan",
    "hypothesis": "Hipotesis",
    "data and assumptions": "Data dan Andaian",
    "evaluation pipeline": "Saluran Penilaian",
    "metrics": "Metrik",
    "baseline comparison": "Perbandingan Garis Dasar",
    "bias and leakage risks": "Risiko Bias dan Kebocoran",
    "robustness checks": "Semakan Keteguhan",
    "failure modes": "Mod Kegagalan",
    "materials and tools": "Bahan dan Alat",
    "style or quality standards": "Piawaian Gaya atau Kualiti",
    "core techniques": "Teknik Teras",
    "process": "Proses",
    "representative cases": "Kes Perwakilan",
    "sensory or output standards": "Piawaian Deria atau Output",
    "common failures and fixes": "Kegagalan Lazim dan Pembetulan",
    "timeline": "Garis Masa",
    "key actors, works, or institutions": "Tokoh, Karya, atau Institusi Utama",
    "causal forces": "Kuasa Sebab Akibat",
    "major transitions": "Peralihan Utama",
    "conflicts or debates": "Konflik atau Perdebatan",
    "legacy and modern relevance": "Warisan dan Kerelevanan Moden",
  },
  hi: {
    "orientation": "सीखने की दिशा",
    "prerequisite map": "पूर्वज्ञान मानचित्र",
    "core concept map": "मुख्य अवधारणा मानचित्र",
    "concept explanations": "अवधारणा व्याख्याएँ",
    "relationships and tradeoffs": "संबंध और समझौते",
    "examples": "उदाहरण",
    "common misconceptions": "सामान्य भ्रांतियाँ",
    "retrieval questions": "स्मरण अभ्यास प्रश्न",
    "next steps": "अगले कदम",
    "core quantities and models": "मुख्य राशियाँ और मॉडल",
    "symbols, units, and dimensions": "प्रतीक, इकाइयाँ और आयाम",
    "formula intuition": "सूत्र की सहज समझ",
    "assumptions and regimes": "मान्यताएँ और लागू क्षेत्र",
    "worked examples": "हल किए गए उदाहरण",
    "edge cases and limiting cases": "किनारी और सीमित मामले",
    "common mistakes": "सामान्य गलतियाँ",
    "minimal working workflow": "न्यूनतम कार्यशील प्रवाह",
    "prerequisite tools and setup": "आवश्यक उपकरण और सेटअप",
    "core tasks": "मुख्य कार्य",
    "step-by-step workflows": "चरणबद्ध कार्यप्रवाह",
    "verification checklist": "सत्यापन सूची",
    "common mistakes and troubleshooting": "सामान्य गलतियाँ और समस्या समाधान",
    "practice tasks": "अभ्यास कार्य",
    "hypothesis": "परिकल्पना",
    "data and assumptions": "डेटा और मान्यताएँ",
    "evaluation pipeline": "मूल्यांकन प्रवाह",
    "metrics": "मापदंड",
    "baseline comparison": "आधाररेखा तुलना",
    "bias and leakage risks": "पक्षपात और रिसाव जोखिम",
    "robustness checks": "मजबूती जाँच",
    "failure modes": "विफलता रूप",
    "materials and tools": "सामग्री और उपकरण",
    "style or quality standards": "शैली या गुणवत्ता मानक",
    "core techniques": "मुख्य तकनीकें",
    "process": "प्रक्रिया",
    "representative cases": "प्रतिनिधि मामले",
    "sensory or output standards": "संवेदी या आउटपुट मानक",
    "common failures and fixes": "सामान्य विफलताएँ और सुधार",
    "timeline": "समयरेखा",
    "key actors, works, or institutions": "मुख्य व्यक्ति, कृतियाँ या संस्थान",
    "causal forces": "कारणकारी शक्तियाँ",
    "major transitions": "मुख्य संक्रमण",
    "conflicts or debates": "संघर्ष या बहसें",
    "legacy and modern relevance": "विरासत और आधुनिक प्रासंगिकता",
  },
  ar: {
    "orientation": "توجيه التعلم",
    "prerequisite map": "خريطة المتطلبات السابقة",
    "core concept map": "خريطة المفاهيم الأساسية",
    "concept explanations": "شرح المفاهيم",
    "relationships and tradeoffs": "العلاقات والمفاضلات",
    "examples": "أمثلة",
    "common misconceptions": "المفاهيم الخاطئة الشائعة",
    "retrieval questions": "أسئلة الاسترجاع",
    "next steps": "الخطوات التالية",
    "core quantities and models": "الكميات والنماذج الأساسية",
    "symbols, units, and dimensions": "الرموز والوحدات والأبعاد",
    "formula intuition": "حدس الصيغ",
    "assumptions and regimes": "الافتراضات ونطاقات التطبيق",
    "worked examples": "أمثلة محلولة",
    "edge cases and limiting cases": "الحالات الحدية وحالات النهاية",
    "common mistakes": "الأخطاء الشائعة",
    "minimal working workflow": "سير عمل أدنى قابل للاستخدام",
    "prerequisite tools and setup": "الأدوات والإعدادات المطلوبة",
    "core tasks": "المهام الأساسية",
    "step-by-step workflows": "سير العمل خطوة بخطوة",
    "verification checklist": "قائمة التحقق",
    "common mistakes and troubleshooting": "الأخطاء الشائعة واستكشاف المشكلات",
    "practice tasks": "مهام تدريبية",
    "hypothesis": "الفرضية",
    "data and assumptions": "البيانات والافتراضات",
    "evaluation pipeline": "خط سير التقييم",
    "metrics": "المقاييس",
    "baseline comparison": "مقارنة خط الأساس",
    "bias and leakage risks": "مخاطر التحيز والتسرب",
    "robustness checks": "اختبارات المتانة",
    "failure modes": "أنماط الفشل",
    "materials and tools": "المواد والأدوات",
    "style or quality standards": "معايير الأسلوب أو الجودة",
    "core techniques": "التقنيات الأساسية",
    "process": "العملية",
    "representative cases": "حالات تمثيلية",
    "sensory or output standards": "معايير حسية أو مخرجات",
    "common failures and fixes": "الإخفاقات الشائعة وإصلاحها",
    "timeline": "الخط الزمني",
    "key actors, works, or institutions": "الفاعلون أو الأعمال أو المؤسسات الرئيسية",
    "causal forces": "القوى السببية",
    "major transitions": "التحولات الكبرى",
    "conflicts or debates": "الصراعات أو النقاشات",
    "legacy and modern relevance": "الإرث والأهمية الحديثة",
  },
  de: {
    "orientation": "Lernorientierung",
    "prerequisite map": "Karte der Vorkenntnisse",
    "core concept map": "Karte der Kernkonzepte",
    "concept explanations": "Konzept-Erklärungen",
    "relationships and tradeoffs": "Beziehungen und Abwägungen",
    "examples": "Beispiele",
    "common misconceptions": "Häufige Missverständnisse",
    "retrieval questions": "Abruffragen",
    "next steps": "Nächste Schritte",
    "core quantities and models": "Kern-Größen und Modelle",
    "symbols, units, and dimensions": "Symbole, Einheiten und Dimensionen",
    "formula intuition": "Formelintuition",
    "assumptions and regimes": "Annahmen und Gültigkeitsbereiche",
    "worked examples": "Durchgerechnete Beispiele",
    "edge cases and limiting cases": "Randfälle und Grenzfälle",
    "common mistakes": "Häufige Fehler",
    "minimal working workflow": "Minimaler funktionsfähiger Ablauf",
    "prerequisite tools and setup": "Erforderliche Werkzeuge und Einrichtung",
    "core tasks": "Kernaufgaben",
    "step-by-step workflows": "Schritt-für-Schritt-Abläufe",
    "verification checklist": "Prüfliste",
    "common mistakes and troubleshooting": "Häufige Fehler und Fehlersuche",
    "practice tasks": "Übungsaufgaben",
    "hypothesis": "Hypothese",
    "data and assumptions": "Daten und Annahmen",
    "evaluation pipeline": "Bewertungsablauf",
    "metrics": "Metriken",
    "baseline comparison": "Vergleich mit der Basislinie",
    "bias and leakage risks": "Risiken durch Verzerrung und Leakage",
    "robustness checks": "Robustheitsprüfungen",
    "failure modes": "Fehlermodi",
    "materials and tools": "Materialien und Werkzeuge",
    "style or quality standards": "Stil- oder Qualitätsstandards",
    "core techniques": "Kerntechniken",
    "process": "Prozess",
    "representative cases": "Repräsentative Fälle",
    "sensory or output standards": "Sinnes- oder Ausgabestandards",
    "common failures and fixes": "Häufige Fehlschläge und Korrekturen",
    "timeline": "Zeitlinie",
    "key actors, works, or institutions": "Schlüsselakteure, Werke oder Institutionen",
    "causal forces": "Kausale Kräfte",
    "major transitions": "Wichtige Übergänge",
    "conflicts or debates": "Konflikte oder Debatten",
    "legacy and modern relevance": "Vermächtnis und heutige Relevanz",
  },
  fr: {
    "orientation": "Orientation d'apprentissage",
    "prerequisite map": "Carte des prérequis",
    "core concept map": "Carte des concepts clés",
    "concept explanations": "Explications des concepts",
    "relationships and tradeoffs": "Relations et compromis",
    "examples": "Exemples",
    "common misconceptions": "Idées reçues courantes",
    "retrieval questions": "Questions de rappel",
    "next steps": "Étapes suivantes",
    "core quantities and models": "Grandeurs et modèles clés",
    "symbols, units, and dimensions": "Symboles, unités et dimensions",
    "formula intuition": "Intuition des formules",
    "assumptions and regimes": "Hypothèses et régimes d'application",
    "worked examples": "Exemples corrigés",
    "edge cases and limiting cases": "Cas limites et cas aux frontières",
    "common mistakes": "Erreurs courantes",
    "minimal working workflow": "Flux de travail minimal fonctionnel",
    "prerequisite tools and setup": "Outils et configuration requis",
    "core tasks": "Tâches clés",
    "step-by-step workflows": "Flux de travail étape par étape",
    "verification checklist": "Liste de vérification",
    "common mistakes and troubleshooting": "Erreurs courantes et dépannage",
    "practice tasks": "Exercices pratiques",
    "hypothesis": "Hypothèse",
    "data and assumptions": "Données et hypothèses",
    "evaluation pipeline": "Chaîne d'évaluation",
    "metrics": "Métriques",
    "baseline comparison": "Comparaison avec la référence",
    "bias and leakage risks": "Risques de biais et de fuite",
    "robustness checks": "Contrôles de robustesse",
    "failure modes": "Modes d'échec",
    "materials and tools": "Matériaux et outils",
    "style or quality standards": "Normes de style ou de qualité",
    "core techniques": "Techniques clés",
    "process": "Processus",
    "representative cases": "Cas représentatifs",
    "sensory or output standards": "Normes sensorielles ou de sortie",
    "common failures and fixes": "Échecs courants et corrections",
    "timeline": "Chronologie",
    "key actors, works, or institutions": "Acteurs, œuvres ou institutions clés",
    "causal forces": "Forces causales",
    "major transitions": "Transitions majeures",
    "conflicts or debates": "Conflits ou débats",
    "legacy and modern relevance": "Héritage et pertinence moderne",
  },
  es: {
    "orientation": "Orientación de aprendizaje",
    "prerequisite map": "Mapa de requisitos previos",
    "core concept map": "Mapa de conceptos centrales",
    "concept explanations": "Explicaciones de conceptos",
    "relationships and tradeoffs": "Relaciones y compensaciones",
    "examples": "Ejemplos",
    "common misconceptions": "Malentendidos comunes",
    "retrieval questions": "Preguntas de recuperación",
    "next steps": "Próximos pasos",
    "core quantities and models": "Magnitudes y modelos centrales",
    "symbols, units, and dimensions": "Símbolos, unidades y dimensiones",
    "formula intuition": "Intuición de las fórmulas",
    "assumptions and regimes": "Supuestos y regímenes de aplicación",
    "worked examples": "Ejemplos resueltos",
    "edge cases and limiting cases": "Casos extremos y casos límite",
    "common mistakes": "Errores comunes",
    "minimal working workflow": "Flujo mínimo funcional",
    "prerequisite tools and setup": "Herramientas y configuración previas",
    "core tasks": "Tareas centrales",
    "step-by-step workflows": "Flujos paso a paso",
    "verification checklist": "Lista de verificación",
    "common mistakes and troubleshooting": "Errores comunes y solución de problemas",
    "practice tasks": "Tareas de práctica",
    "hypothesis": "Hipótesis",
    "data and assumptions": "Datos y supuestos",
    "evaluation pipeline": "Flujo de evaluación",
    "metrics": "Métricas",
    "baseline comparison": "Comparación con la línea base",
    "bias and leakage risks": "Riesgos de sesgo y fuga",
    "robustness checks": "Comprobaciones de robustez",
    "failure modes": "Modos de fallo",
    "materials and tools": "Materiales y herramientas",
    "style or quality standards": "Estándares de estilo o calidad",
    "core techniques": "Técnicas centrales",
    "process": "Proceso",
    "representative cases": "Casos representativos",
    "sensory or output standards": "Estándares sensoriales o de salida",
    "common failures and fixes": "Fallos comunes y correcciones",
    "timeline": "Cronología",
    "key actors, works, or institutions": "Actores, obras o instituciones clave",
    "causal forces": "Fuerzas causales",
    "major transitions": "Transiciones principales",
    "conflicts or debates": "Conflictos o debates",
    "legacy and modern relevance": "Legado y relevancia moderna",
  },
  it: {
    "orientation": "Orientamento allo studio",
    "prerequisite map": "Mappa dei prerequisiti",
    "core concept map": "Mappa dei concetti centrali",
    "concept explanations": "Spiegazioni dei concetti",
    "relationships and tradeoffs": "Relazioni e compromessi",
    "examples": "Esempi",
    "common misconceptions": "Fraintendimenti comuni",
    "retrieval questions": "Domande di recupero",
    "next steps": "Passi successivi",
    "core quantities and models": "Quantità e modelli centrali",
    "symbols, units, and dimensions": "Simboli, unità e dimensioni",
    "formula intuition": "Intuizione delle formule",
    "assumptions and regimes": "Assunzioni e regimi di validità",
    "worked examples": "Esempi svolti",
    "edge cases and limiting cases": "Casi limite e casi estremi",
    "common mistakes": "Errori comuni",
    "minimal working workflow": "Flusso minimo funzionante",
    "prerequisite tools and setup": "Strumenti e configurazione preliminari",
    "core tasks": "Compiti centrali",
    "step-by-step workflows": "Flussi passo per passo",
    "verification checklist": "Lista di verifica",
    "common mistakes and troubleshooting": "Errori comuni e risoluzione dei problemi",
    "practice tasks": "Esercizi pratici",
    "hypothesis": "Ipotesi",
    "data and assumptions": "Dati e assunzioni",
    "evaluation pipeline": "Pipeline di valutazione",
    "metrics": "Metriche",
    "baseline comparison": "Confronto con la baseline",
    "bias and leakage risks": "Rischi di bias e leakage",
    "robustness checks": "Controlli di robustezza",
    "failure modes": "Modalità di fallimento",
    "materials and tools": "Materiali e strumenti",
    "style or quality standards": "Standard di stile o qualità",
    "core techniques": "Tecniche centrali",
    "process": "Processo",
    "representative cases": "Casi rappresentativi",
    "sensory or output standards": "Standard sensoriali o di output",
    "common failures and fixes": "Fallimenti comuni e correzioni",
    "timeline": "Linea temporale",
    "key actors, works, or institutions": "Attori, opere o istituzioni chiave",
    "causal forces": "Forze causali",
    "major transitions": "Transizioni principali",
    "conflicts or debates": "Conflitti o dibattiti",
    "legacy and modern relevance": "Eredità e rilevanza moderna",
  },
  pt: {
    "orientation": "Orientação de aprendizagem",
    "prerequisite map": "Mapa de pré-requisitos",
    "core concept map": "Mapa de conceitos centrais",
    "concept explanations": "Explicações de conceitos",
    "relationships and tradeoffs": "Relações e trade-offs",
    "examples": "Exemplos",
    "common misconceptions": "Equívocos comuns",
    "retrieval questions": "Perguntas de recuperação",
    "next steps": "Próximos passos",
    "core quantities and models": "Quantidades e modelos centrais",
    "symbols, units, and dimensions": "Símbolos, unidades e dimensões",
    "formula intuition": "Intuição das fórmulas",
    "assumptions and regimes": "Suposições e regimes de aplicação",
    "worked examples": "Exemplos resolvidos",
    "edge cases and limiting cases": "Casos de borda e casos limite",
    "common mistakes": "Erros comuns",
    "minimal working workflow": "Fluxo mínimo funcional",
    "prerequisite tools and setup": "Ferramentas e configuração prévias",
    "core tasks": "Tarefas centrais",
    "step-by-step workflows": "Fluxos passo a passo",
    "verification checklist": "Lista de verificação",
    "common mistakes and troubleshooting": "Erros comuns e solução de problemas",
    "practice tasks": "Tarefas práticas",
    "hypothesis": "Hipótese",
    "data and assumptions": "Dados e suposições",
    "evaluation pipeline": "Pipeline de avaliação",
    "metrics": "Métricas",
    "baseline comparison": "Comparação com baseline",
    "bias and leakage risks": "Riscos de viés e vazamento",
    "robustness checks": "Verificações de robustez",
    "failure modes": "Modos de falha",
    "materials and tools": "Materiais e ferramentas",
    "style or quality standards": "Padrões de estilo ou qualidade",
    "core techniques": "Técnicas centrais",
    "process": "Processo",
    "representative cases": "Casos representativos",
    "sensory or output standards": "Padrões sensoriais ou de saída",
    "common failures and fixes": "Falhas comuns e correções",
    "timeline": "Linha do tempo",
    "key actors, works, or institutions": "Atores, obras ou instituições-chave",
    "causal forces": "Forças causais",
    "major transitions": "Transições principais",
    "conflicts or debates": "Conflitos ou debates",
    "legacy and modern relevance": "Legado e relevância moderna",
  },
  nl: {
    "orientation": "Leeroriëntatie",
    "prerequisite map": "Kaart van voorkennis",
    "core concept map": "Kaart van kernconcepten",
    "concept explanations": "Uitleg van concepten",
    "relationships and tradeoffs": "Relaties en afwegingen",
    "examples": "Voorbeelden",
    "common misconceptions": "Veelvoorkomende misvattingen",
    "retrieval questions": "Ophaalvragen",
    "next steps": "Volgende stappen",
    "core quantities and models": "Kern-grootheden en modellen",
    "symbols, units, and dimensions": "Symbolen, eenheden en dimensies",
    "formula intuition": "Formule-intuïtie",
    "assumptions and regimes": "Aannames en toepassingsgebieden",
    "worked examples": "Uitgewerkte voorbeelden",
    "edge cases and limiting cases": "Randgevallen en limietgevallen",
    "common mistakes": "Veelvoorkomende fouten",
    "minimal working workflow": "Minimale werkende workflow",
    "prerequisite tools and setup": "Benodigde tools en configuratie",
    "core tasks": "Kerntaken",
    "step-by-step workflows": "Stapsgewijze workflows",
    "verification checklist": "Verificatiechecklist",
    "common mistakes and troubleshooting": "Veelvoorkomende fouten en probleemoplossing",
    "practice tasks": "Oefentaken",
    "hypothesis": "Hypothese",
    "data and assumptions": "Data en aannames",
    "evaluation pipeline": "Evaluatiepipeline",
    "metrics": "Metrieken",
    "baseline comparison": "Vergelijking met baseline",
    "bias and leakage risks": "Risico's op bias en leakage",
    "robustness checks": "Robuustheidscontroles",
    "failure modes": "Faalmodi",
    "materials and tools": "Materialen en tools",
    "style or quality standards": "Stijl- of kwaliteitsstandaarden",
    "core techniques": "Kerntechnieken",
    "process": "Proces",
    "representative cases": "Representatieve gevallen",
    "sensory or output standards": "Sensorische of outputstandaarden",
    "common failures and fixes": "Veelvoorkomende fouten en oplossingen",
    "timeline": "Tijdlijn",
    "key actors, works, or institutions": "Belangrijke actoren, werken of instellingen",
    "causal forces": "Causale krachten",
    "major transitions": "Belangrijke overgangen",
    "conflicts or debates": "Conflicten of debatten",
    "legacy and modern relevance": "Erfenis en moderne relevantie",
  },
  sv: {
    "orientation": "Lärandeorientering",
    "prerequisite map": "Karta över förkunskaper",
    "core concept map": "Karta över kärnbegrepp",
    "concept explanations": "Begreppsförklaringar",
    "relationships and tradeoffs": "Relationer och avvägningar",
    "examples": "Exempel",
    "common misconceptions": "Vanliga missuppfattningar",
    "retrieval questions": "Återkallningsfrågor",
    "next steps": "Nästa steg",
    "core quantities and models": "Centrala storheter och modeller",
    "symbols, units, and dimensions": "Symboler, enheter och dimensioner",
    "formula intuition": "Formelintuition",
    "assumptions and regimes": "Antaganden och tillämpningsområden",
    "worked examples": "Genomarbetade exempel",
    "edge cases and limiting cases": "Kantfall och gränsfall",
    "common mistakes": "Vanliga misstag",
    "minimal working workflow": "Minsta fungerande arbetsflöde",
    "prerequisite tools and setup": "Nödvändiga verktyg och inställningar",
    "core tasks": "Kärnuppgifter",
    "step-by-step workflows": "Stegvisa arbetsflöden",
    "verification checklist": "Verifieringschecklista",
    "common mistakes and troubleshooting": "Vanliga misstag och felsökning",
    "practice tasks": "Övningsuppgifter",
    "hypothesis": "Hypotes",
    "data and assumptions": "Data och antaganden",
    "evaluation pipeline": "Utvärderingsflöde",
    "metrics": "Mått",
    "baseline comparison": "Jämförelse med baslinje",
    "bias and leakage risks": "Risker för bias och läckage",
    "robustness checks": "Robusthetskontroller",
    "failure modes": "Felllägen",
    "materials and tools": "Material och verktyg",
    "style or quality standards": "Stil- eller kvalitetsstandarder",
    "core techniques": "Kärntekniker",
    "process": "Process",
    "representative cases": "Representativa fall",
    "sensory or output standards": "Sensoriska eller outputstandarder",
    "common failures and fixes": "Vanliga fel och korrigeringar",
    "timeline": "Tidslinje",
    "key actors, works, or institutions": "Nyckelaktörer, verk eller institutioner",
    "causal forces": "Kausala krafter",
    "major transitions": "Stora övergångar",
    "conflicts or debates": "Konflikter eller debatter",
    "legacy and modern relevance": "Arv och modern relevans",
  },
  fi: {
    "orientation": "Oppimisen suuntaus",
    "prerequisite map": "Esitietokartta",
    "core concept map": "Keskeisten käsitteiden kartta",
    "concept explanations": "Käsitteiden selitykset",
    "relationships and tradeoffs": "Suhteet ja kompromissit",
    "examples": "Esimerkit",
    "common misconceptions": "Yleiset väärinkäsitykset",
    "retrieval questions": "Mieleenpalautuskysymykset",
    "next steps": "Seuraavat vaiheet",
    "core quantities and models": "Keskeiset suureet ja mallit",
    "symbols, units, and dimensions": "Symbolit, yksiköt ja dimensiot",
    "formula intuition": "Kaavojen intuitio",
    "assumptions and regimes": "Oletukset ja soveltamisalueet",
    "worked examples": "Ratkaistut esimerkit",
    "edge cases and limiting cases": "Reuna- ja rajatapaukset",
    "common mistakes": "Yleiset virheet",
    "minimal working workflow": "Vähimmäistoimiva työnkulku",
    "prerequisite tools and setup": "Tarvittavat työkalut ja asetukset",
    "core tasks": "Keskeiset tehtävät",
    "step-by-step workflows": "Vaiheittaiset työnkulut",
    "verification checklist": "Varmistuslista",
    "common mistakes and troubleshooting": "Yleiset virheet ja vianmääritys",
    "practice tasks": "Harjoitustehtävät",
    "hypothesis": "Hypoteesi",
    "data and assumptions": "Data ja oletukset",
    "evaluation pipeline": "Arviointiputki",
    "metrics": "Mittarit",
    "baseline comparison": "Vertailu perustasoon",
    "bias and leakage risks": "Harhan ja vuodon riskit",
    "robustness checks": "Robustiustarkistukset",
    "failure modes": "Vikatilat",
    "materials and tools": "Materiaalit ja työkalut",
    "style or quality standards": "Tyyli- tai laatustandardit",
    "core techniques": "Keskeiset tekniikat",
    "process": "Prosessi",
    "representative cases": "Edustavat tapaukset",
    "sensory or output standards": "Aistinvaraiset tai tulostestandardit",
    "common failures and fixes": "Yleiset epäonnistumiset ja korjaukset",
    "timeline": "Aikajana",
    "key actors, works, or institutions": "Keskeiset toimijat, teokset tai instituutiot",
    "causal forces": "Kausaaliset voimat",
    "major transitions": "Suuret siirtymät",
    "conflicts or debates": "Konfliktit tai väittelyt",
    "legacy and modern relevance": "Perintö ja nykyinen merkitys",
  },
  pl: {
    "orientation": "Orientacja w nauce",
    "prerequisite map": "Mapa wiedzy wstępnej",
    "core concept map": "Mapa kluczowych pojęć",
    "concept explanations": "Wyjaśnienia pojęć",
    "relationships and tradeoffs": "Relacje i kompromisy",
    "examples": "Przykłady",
    "common misconceptions": "Częste nieporozumienia",
    "retrieval questions": "Pytania przypominające",
    "next steps": "Następne kroki",
    "core quantities and models": "Kluczowe wielkości i modele",
    "symbols, units, and dimensions": "Symbole, jednostki i wymiary",
    "formula intuition": "Intuicja wzorów",
    "assumptions and regimes": "Założenia i zakresy zastosowania",
    "worked examples": "Przykłady rozwiązane",
    "edge cases and limiting cases": "Przypadki brzegowe i graniczne",
    "common mistakes": "Częste błędy",
    "minimal working workflow": "Minimalny działający przepływ pracy",
    "prerequisite tools and setup": "Wymagane narzędzia i konfiguracja",
    "core tasks": "Kluczowe zadania",
    "step-by-step workflows": "Przepływy pracy krok po kroku",
    "verification checklist": "Lista kontrolna weryfikacji",
    "common mistakes and troubleshooting": "Częste błędy i rozwiązywanie problemów",
    "practice tasks": "Zadania praktyczne",
    "hypothesis": "Hipoteza",
    "data and assumptions": "Dane i założenia",
    "evaluation pipeline": "Proces oceny",
    "metrics": "Metryki",
    "baseline comparison": "Porównanie z bazą odniesienia",
    "bias and leakage risks": "Ryzyka stronniczości i wycieku",
    "robustness checks": "Kontrole odporności",
    "failure modes": "Tryby awarii",
    "materials and tools": "Materiały i narzędzia",
    "style or quality standards": "Standardy stylu lub jakości",
    "core techniques": "Kluczowe techniki",
    "process": "Proces",
    "representative cases": "Przypadki reprezentatywne",
    "sensory or output standards": "Standardy sensoryczne lub wyjściowe",
    "common failures and fixes": "Częste niepowodzenia i poprawki",
    "timeline": "Oś czasu",
    "key actors, works, or institutions": "Kluczowi aktorzy, dzieła lub instytucje",
    "causal forces": "Siły przyczynowe",
    "major transitions": "Główne przejścia",
    "conflicts or debates": "Konflikty lub debaty",
    "legacy and modern relevance": "Dziedzictwo i współczesna istotność",
  },
  tr: {
    "orientation": "Öğrenme Konumlandırması",
    "prerequisite map": "Ön Bilgi Haritası",
    "core concept map": "Temel Kavram Haritası",
    "concept explanations": "Kavram Açıklamaları",
    "relationships and tradeoffs": "İlişkiler ve Ödünleşimler",
    "examples": "Örnekler",
    "common misconceptions": "Yaygın Yanlış Anlamalar",
    "retrieval questions": "Hatırlama Soruları",
    "next steps": "Sonraki Adımlar",
    "core quantities and models": "Temel Nicelikler ve Modeller",
    "symbols, units, and dimensions": "Semboller, Birimler ve Boyutlar",
    "formula intuition": "Formül Sezgisi",
    "assumptions and regimes": "Varsayımlar ve Geçerlilik Alanları",
    "worked examples": "Çözümlü Örnekler",
    "edge cases and limiting cases": "Uç Durumlar ve Sınır Durumları",
    "common mistakes": "Yaygın Hatalar",
    "minimal working workflow": "Minimum Çalışan İş Akışı",
    "prerequisite tools and setup": "Gerekli Araçlar ve Kurulum",
    "core tasks": "Temel Görevler",
    "step-by-step workflows": "Adım Adım İş Akışları",
    "verification checklist": "Doğrulama Kontrol Listesi",
    "common mistakes and troubleshooting": "Yaygın Hatalar ve Sorun Giderme",
    "practice tasks": "Pratik Görevleri",
    "hypothesis": "Hipotez",
    "data and assumptions": "Veri ve Varsayımlar",
    "evaluation pipeline": "Değerlendirme Hattı",
    "metrics": "Metrikler",
    "baseline comparison": "Temel Çizgi Karşılaştırması",
    "bias and leakage risks": "Yanlılık ve Sızıntı Riskleri",
    "robustness checks": "Sağlamlık Kontrolleri",
    "failure modes": "Başarısızlık Biçimleri",
    "materials and tools": "Malzemeler ve Araçlar",
    "style or quality standards": "Stil veya Kalite Standartları",
    "core techniques": "Temel Teknikler",
    "process": "Süreç",
    "representative cases": "Temsilî Vakalar",
    "sensory or output standards": "Duyusal veya Çıktı Standartları",
    "common failures and fixes": "Yaygın Başarısızlıklar ve Düzeltmeler",
    "timeline": "Zaman Çizelgesi",
    "key actors, works, or institutions": "Kilit Aktörler, Eserler veya Kurumlar",
    "causal forces": "Nedensel Güçler",
    "major transitions": "Başlıca Geçişler",
    "conflicts or debates": "Çatışmalar veya Tartışmalar",
    "legacy and modern relevance": "Miras ve Modern İlgililik",
  },
  ru: {
    "orientation": "Учебная ориентация",
    "prerequisite map": "Карта предварительных знаний",
    "core concept map": "Карта ключевых понятий",
    "concept explanations": "Объяснения понятий",
    "relationships and tradeoffs": "Связи и компромиссы",
    "examples": "Примеры",
    "common misconceptions": "Распространенные заблуждения",
    "retrieval questions": "Вопросы для воспроизведения",
    "next steps": "Следующие шаги",
    "core quantities and models": "Ключевые величины и модели",
    "symbols, units, and dimensions": "Символы, единицы и размерности",
    "formula intuition": "Интуиция формул",
    "assumptions and regimes": "Предположения и области применимости",
    "worked examples": "Разобранные примеры",
    "edge cases and limiting cases": "Краевые и предельные случаи",
    "common mistakes": "Распространенные ошибки",
    "minimal working workflow": "Минимальный рабочий процесс",
    "prerequisite tools and setup": "Необходимые инструменты и настройка",
    "core tasks": "Ключевые задачи",
    "step-by-step workflows": "Пошаговые рабочие процессы",
    "verification checklist": "Контрольный список проверки",
    "common mistakes and troubleshooting": "Распространенные ошибки и устранение неполадок",
    "practice tasks": "Практические задания",
    "hypothesis": "Гипотеза",
    "data and assumptions": "Данные и предположения",
    "evaluation pipeline": "Процесс оценки",
    "metrics": "Метрики",
    "baseline comparison": "Сравнение с базовой линией",
    "bias and leakage risks": "Риски смещения и утечки",
    "robustness checks": "Проверки устойчивости",
    "failure modes": "Режимы отказа",
    "materials and tools": "Материалы и инструменты",
    "style or quality standards": "Стандарты стиля или качества",
    "core techniques": "Ключевые техники",
    "process": "Процесс",
    "representative cases": "Репрезентативные случаи",
    "sensory or output standards": "Сенсорные или выходные стандарты",
    "common failures and fixes": "Распространенные сбои и исправления",
    "timeline": "Хронология",
    "key actors, works, or institutions": "Ключевые участники, произведения или институты",
    "causal forces": "Причинные силы",
    "major transitions": "Основные переходы",
    "conflicts or debates": "Конфликты или дискуссии",
    "legacy and modern relevance": "Наследие и современная значимость",
  },
};

const LOCALIZED_UNIT_FIELD_TITLES: Record<string, Record<string, string>> = {
  ja: {
    "definition and intuition": "定義と直感",
    "why it exists": "存在する理由",
    "problem it solves": "解決する問題",
    "prerequisites": "前提知識",
    "concrete example": "具体例",
    "relationship to neighboring concepts": "隣接概念との関係",
    "common misconception": "よくある誤解",
    "definition": "定義",
    "intuition": "直感",
    "symbols and units": "記号と単位",
    "assumptions": "仮定",
    "when the model applies": "モデルが適用できる条件",
    "simple numerical example": "簡単な数値例",
    "what breaks when assumptions fail": "仮定が崩れると何が破綻するか",
    "goal": "目的",
    "when to use it": "使う場面",
    "steps": "手順",
    "menu path or shortcut if applicable": "メニュー経路またはショートカット",
    "expected result": "期待される結果",
    "how to verify the output": "出力の検証方法",
    "what it measures": "測定するもの",
    "why it matters": "重要な理由",
    "how to compute or test it": "計算またはテスト方法",
    "how it fails": "失敗の仕方",
    "example": "例",
    "diagnostic check": "診断チェック",
    "purpose": "目的",
    "materials or conditions": "材料または条件",
    "sensory or quality standard": "感覚または品質基準",
    "common failure": "よくある失敗",
    "fix": "修正",
    "period or transition": "時期または転換",
    "what changed": "変化したこと",
    "why it changed": "変化した理由",
    "key actors or examples": "主要人物または例",
    "broader context": "より広い文脈",
    "modern relevance": "現代的意義",
  },
  ko: {
    "definition and intuition": "정의와 직관",
    "why it exists": "존재 이유",
    "problem it solves": "해결하는 문제",
    "prerequisites": "선수 지식",
    "concrete example": "구체적 예시",
    "relationship to neighboring concepts": "인접 개념과의 관계",
    "common misconception": "흔한 오해",
    "definition": "정의",
    "intuition": "직관",
    "symbols and units": "기호와 단위",
    "assumptions": "가정",
    "when the model applies": "모델 적용 조건",
    "simple numerical example": "간단한 수치 예시",
    "what breaks when assumptions fail": "가정이 깨질 때 생기는 문제",
    "goal": "목표",
    "when to use it": "사용 시점",
    "steps": "단계",
    "menu path or shortcut if applicable": "메뉴 경로 또는 단축키",
    "expected result": "예상 결과",
    "how to verify the output": "출력 검증 방법",
    "what it measures": "측정 대상",
    "why it matters": "중요한 이유",
    "how to compute or test it": "계산 또는 테스트 방법",
    "how it fails": "실패 방식",
    "example": "예시",
    "diagnostic check": "진단 점검",
    "purpose": "목적",
    "materials or conditions": "재료 또는 조건",
    "sensory or quality standard": "감각 또는 품질 기준",
    "common failure": "흔한 실패",
    "fix": "수정",
    "period or transition": "시기 또는 전환",
    "what changed": "무엇이 바뀌었는가",
    "why it changed": "왜 바뀌었는가",
    "key actors or examples": "주요 인물 또는 예시",
    "broader context": "더 넓은 맥락",
    "modern relevance": "현대적 관련성",
  },
  vi: {
    "definition and intuition": "Định nghĩa và trực giác",
    "why it exists": "Vì sao nó tồn tại",
    "problem it solves": "Vấn đề nó giải quyết",
    "prerequisites": "Kiến thức tiên quyết",
    "concrete example": "Ví dụ cụ thể",
    "relationship to neighboring concepts": "Quan hệ với khái niệm lân cận",
    "common misconception": "Hiểu lầm thường gặp",
    "definition": "Định nghĩa",
    "intuition": "Trực giác",
    "symbols and units": "Ký hiệu và đơn vị",
    "assumptions": "Giả định",
    "when the model applies": "Khi mô hình áp dụng",
    "simple numerical example": "Ví dụ số đơn giản",
    "what breaks when assumptions fail": "Điều gì hỏng khi giả định sai",
    "goal": "Mục tiêu",
    "when to use it": "Khi nào dùng",
    "steps": "Các bước",
    "menu path or shortcut if applicable": "Đường dẫn menu hoặc phím tắt",
    "expected result": "Kết quả kỳ vọng",
    "how to verify the output": "Cách xác minh đầu ra",
    "what it measures": "Nó đo điều gì",
    "why it matters": "Vì sao quan trọng",
    "how to compute or test it": "Cách tính hoặc kiểm thử",
    "how it fails": "Cách nó thất bại",
    "example": "Ví dụ",
    "diagnostic check": "Kiểm tra chẩn đoán",
    "purpose": "Mục đích",
    "materials or conditions": "Vật liệu hoặc điều kiện",
    "sensory or quality standard": "Chuẩn cảm quan hoặc chất lượng",
    "common failure": "Lỗi thường gặp",
    "fix": "Cách sửa",
    "period or transition": "Giai đoạn hoặc chuyển đổi",
    "what changed": "Điều gì thay đổi",
    "why it changed": "Vì sao thay đổi",
    "key actors or examples": "Nhân vật hoặc ví dụ chính",
    "broader context": "Bối cảnh rộng hơn",
    "modern relevance": "Ý nghĩa hiện đại",
  },
  th: {
    "definition and intuition": "นิยามและสัญชาตญาณ",
    "why it exists": "เหตุผลที่มีอยู่",
    "problem it solves": "ปัญหาที่แก้",
    "prerequisites": "ความรู้พื้นฐาน",
    "concrete example": "ตัวอย่างที่เป็นรูปธรรม",
    "relationship to neighboring concepts": "ความสัมพันธ์กับแนวคิดใกล้เคียง",
    "common misconception": "ความเข้าใจผิดที่พบบ่อย",
    "definition": "นิยาม",
    "intuition": "สัญชาตญาณ",
    "symbols and units": "สัญลักษณ์และหน่วย",
    "assumptions": "สมมติฐาน",
    "when the model applies": "เงื่อนไขที่ใช้โมเดลได้",
    "simple numerical example": "ตัวอย่างตัวเลขง่าย",
    "what breaks when assumptions fail": "สิ่งที่พังเมื่อสมมติฐานผิด",
    "goal": "เป้าหมาย",
    "when to use it": "ควรใช้เมื่อใด",
    "steps": "ขั้นตอน",
    "menu path or shortcut if applicable": "เส้นทางเมนูหรือปุ่มลัด",
    "expected result": "ผลลัพธ์ที่คาดหวัง",
    "how to verify the output": "วิธีตรวจสอบผลลัพธ์",
    "what it measures": "สิ่งที่วัด",
    "why it matters": "เหตุผลที่สำคัญ",
    "how to compute or test it": "วิธีคำนวณหรือทดสอบ",
    "how it fails": "วิธีที่ล้มเหลว",
    "example": "ตัวอย่าง",
    "diagnostic check": "การตรวจวินิจฉัย",
    "purpose": "วัตถุประสงค์",
    "materials or conditions": "วัสดุหรือเงื่อนไข",
    "sensory or quality standard": "มาตรฐานประสาทสัมผัสหรือคุณภาพ",
    "common failure": "ความล้มเหลวที่พบบ่อย",
    "fix": "วิธีแก้",
    "period or transition": "ช่วงเวลา หรือ การเปลี่ยนผ่าน",
    "what changed": "สิ่งที่เปลี่ยน",
    "why it changed": "เหตุผลที่เปลี่ยน",
    "key actors or examples": "ผู้เกี่ยวข้องหลักหรือตัวอย่าง",
    "broader context": "บริบทที่กว้างขึ้น",
    "modern relevance": "ความเกี่ยวข้องในปัจจุบัน",
  },
  id: {
    "definition and intuition": "Definisi dan intuisi",
    "why it exists": "Mengapa ini ada",
    "problem it solves": "Masalah yang diselesaikan",
    "prerequisites": "Prasyarat",
    "concrete example": "Contoh konkret",
    "relationship to neighboring concepts": "Hubungan dengan konsep terkait",
    "common misconception": "Kesalahpahaman umum",
    "definition": "Definisi",
    "intuition": "Intuisi",
    "symbols and units": "Simbol dan satuan",
    "assumptions": "Asumsi",
    "when the model applies": "Kapan model berlaku",
    "simple numerical example": "Contoh numerik sederhana",
    "what breaks when assumptions fail": "Apa yang rusak saat asumsi gagal",
    "goal": "Tujuan",
    "when to use it": "Kapan menggunakannya",
    "steps": "Langkah",
    "menu path or shortcut if applicable": "Jalur menu atau pintasan",
    "expected result": "Hasil yang diharapkan",
    "how to verify the output": "Cara memverifikasi output",
    "what it measures": "Apa yang diukur",
    "why it matters": "Mengapa penting",
    "how to compute or test it": "Cara menghitung atau menguji",
    "how it fails": "Bagaimana gagal",
    "example": "Contoh",
    "diagnostic check": "Pemeriksaan diagnostik",
    "purpose": "Tujuan",
    "materials or conditions": "Bahan atau kondisi",
    "sensory or quality standard": "Standar sensorik atau kualitas",
    "common failure": "Kegagalan umum",
    "fix": "Perbaikan",
    "period or transition": "Periode atau transisi",
    "what changed": "Apa yang berubah",
    "why it changed": "Mengapa berubah",
    "key actors or examples": "Aktor kunci atau contoh",
    "broader context": "Konteks lebih luas",
    "modern relevance": "Relevansi modern",
  },
  ms: {
    "definition and intuition": "Definisi dan intuisi",
    "why it exists": "Mengapa ia wujud",
    "problem it solves": "Masalah yang diselesaikan",
    "prerequisites": "Prasyarat",
    "concrete example": "Contoh konkrit",
    "relationship to neighboring concepts": "Hubungan dengan konsep berdekatan",
    "common misconception": "Salah faham lazim",
    "definition": "Definisi",
    "intuition": "Intuisi",
    "symbols and units": "Simbol dan unit",
    "assumptions": "Andaian",
    "when the model applies": "Bila model terpakai",
    "simple numerical example": "Contoh angka mudah",
    "what breaks when assumptions fail": "Apa yang rosak apabila andaian gagal",
    "goal": "Matlamat",
    "when to use it": "Bila menggunakannya",
    "steps": "Langkah",
    "menu path or shortcut if applicable": "Laluan menu atau pintasan",
    "expected result": "Hasil dijangka",
    "how to verify the output": "Cara mengesahkan output",
    "what it measures": "Apa yang diukur",
    "why it matters": "Mengapa penting",
    "how to compute or test it": "Cara mengira atau menguji",
    "how it fails": "Bagaimana ia gagal",
    "example": "Contoh",
    "diagnostic check": "Semakan diagnostik",
    "purpose": "Tujuan",
    "materials or conditions": "Bahan atau syarat",
    "sensory or quality standard": "Piawaian deria atau kualiti",
    "common failure": "Kegagalan lazim",
    "fix": "Pembetulan",
    "period or transition": "Tempoh atau peralihan",
    "what changed": "Apa yang berubah",
    "why it changed": "Mengapa ia berubah",
    "key actors or examples": "Tokoh utama atau contoh",
    "broader context": "Konteks lebih luas",
    "modern relevance": "Kerelevanan moden",
  },
  hi: {
    "definition and intuition": "परिभाषा और सहज समझ",
    "why it exists": "यह क्यों मौजूद है",
    "problem it solves": "यह कौन सी समस्या हल करता है",
    "prerequisites": "पूर्वापेक्षाएँ",
    "concrete example": "ठोस उदाहरण",
    "relationship to neighboring concepts": "पास की अवधारणाओं से संबंध",
    "common misconception": "सामान्य भ्रांति",
    "definition": "परिभाषा",
    "intuition": "सहज समझ",
    "symbols and units": "प्रतीक और इकाइयाँ",
    "assumptions": "मान्यताएँ",
    "when the model applies": "मॉडल कब लागू होता है",
    "simple numerical example": "सरल संख्यात्मक उदाहरण",
    "what breaks when assumptions fail": "मान्यताएँ टूटने पर क्या बिगड़ता है",
    "goal": "लक्ष्य",
    "when to use it": "कब उपयोग करें",
    "steps": "चरण",
    "menu path or shortcut if applicable": "मेनू पथ या शॉर्टकट",
    "expected result": "अपेक्षित परिणाम",
    "how to verify the output": "आउटपुट कैसे सत्यापित करें",
    "what it measures": "यह क्या मापता है",
    "why it matters": "यह क्यों महत्वपूर्ण है",
    "how to compute or test it": "कैसे गणना या परीक्षण करें",
    "how it fails": "यह कैसे विफल होता है",
    "example": "उदाहरण",
    "diagnostic check": "नैदानिक जाँच",
    "purpose": "उद्देश्य",
    "materials or conditions": "सामग्री या स्थितियाँ",
    "sensory or quality standard": "संवेदी या गुणवत्ता मानक",
    "common failure": "सामान्य विफलता",
    "fix": "सुधार",
    "period or transition": "काल या संक्रमण",
    "what changed": "क्या बदला",
    "why it changed": "क्यों बदला",
    "key actors or examples": "मुख्य पात्र या उदाहरण",
    "broader context": "व्यापक संदर्भ",
    "modern relevance": "आधुनिक प्रासंगिकता",
  },
  ar: {
    "definition and intuition": "التعريف والحدس",
    "why it exists": "لماذا يوجد",
    "problem it solves": "المشكلة التي يحلها",
    "prerequisites": "المتطلبات السابقة",
    "concrete example": "مثال ملموس",
    "relationship to neighboring concepts": "العلاقة بالمفاهيم المجاورة",
    "common misconception": "تصور خاطئ شائع",
    "definition": "التعريف",
    "intuition": "الحدس",
    "symbols and units": "الرموز والوحدات",
    "assumptions": "الافتراضات",
    "when the model applies": "متى ينطبق النموذج",
    "simple numerical example": "مثال عددي بسيط",
    "what breaks when assumptions fail": "ما الذي ينهار عند فشل الافتراضات",
    "goal": "الهدف",
    "when to use it": "متى تستخدمه",
    "steps": "الخطوات",
    "menu path or shortcut if applicable": "مسار القائمة أو الاختصار",
    "expected result": "النتيجة المتوقعة",
    "how to verify the output": "كيفية التحقق من المخرجات",
    "what it measures": "ما الذي يقيسه",
    "why it matters": "لماذا هو مهم",
    "how to compute or test it": "كيفية حسابه أو اختباره",
    "how it fails": "كيف يفشل",
    "example": "مثال",
    "diagnostic check": "فحص تشخيصي",
    "purpose": "الغرض",
    "materials or conditions": "المواد أو الشروط",
    "sensory or quality standard": "معيار حسي أو جودة",
    "common failure": "فشل شائع",
    "fix": "إصلاح",
    "period or transition": "فترة أو انتقال",
    "what changed": "ما الذي تغير",
    "why it changed": "لماذا تغير",
    "key actors or examples": "فاعلون رئيسيون أو أمثلة",
    "broader context": "السياق الأوسع",
    "modern relevance": "الأهمية الحديثة",
  },
  de: {
    "definition and intuition": "Definition und Intuition",
    "why it exists": "Warum es existiert",
    "problem it solves": "Problem, das es löst",
    "prerequisites": "Voraussetzungen",
    "concrete example": "Konkretes Beispiel",
    "relationship to neighboring concepts": "Beziehung zu benachbarten Konzepten",
    "common misconception": "Häufiges Missverständnis",
    "definition": "Definition",
    "intuition": "Intuition",
    "symbols and units": "Symbole und Einheiten",
    "assumptions": "Annahmen",
    "when the model applies": "Wann das Modell gilt",
    "simple numerical example": "Einfaches Zahlenbeispiel",
    "what breaks when assumptions fail": "Was bricht, wenn Annahmen scheitern",
    "goal": "Ziel",
    "when to use it": "Wann man es verwendet",
    "steps": "Schritte",
    "menu path or shortcut if applicable": "Menüpfad oder Tastenkürzel",
    "expected result": "Erwartetes Ergebnis",
    "how to verify the output": "Wie man die Ausgabe prüft",
    "what it measures": "Was es misst",
    "why it matters": "Warum es wichtig ist",
    "how to compute or test it": "Wie man es berechnet oder testet",
    "how it fails": "Wie es fehlschlägt",
    "example": "Beispiel",
    "diagnostic check": "Diagnoseprüfung",
    "purpose": "Zweck",
    "materials or conditions": "Materialien oder Bedingungen",
    "sensory or quality standard": "Sinnes- oder Qualitätsstandard",
    "common failure": "Häufiger Fehlschlag",
    "fix": "Korrektur",
    "period or transition": "Periode oder Übergang",
    "what changed": "Was sich geändert hat",
    "why it changed": "Warum es sich geändert hat",
    "key actors or examples": "Schlüsselakteure oder Beispiele",
    "broader context": "Breiterer Kontext",
    "modern relevance": "Heutige Relevanz",
  },
  fr: {
    "definition and intuition": "Définition et intuition",
    "why it exists": "Pourquoi cela existe",
    "problem it solves": "Problème résolu",
    "prerequisites": "Prérequis",
    "concrete example": "Exemple concret",
    "relationship to neighboring concepts": "Relation avec les concepts voisins",
    "common misconception": "Idée reçue courante",
    "definition": "Définition",
    "intuition": "Intuition",
    "symbols and units": "Symboles et unités",
    "assumptions": "Hypothèses",
    "when the model applies": "Quand le modèle s'applique",
    "simple numerical example": "Exemple numérique simple",
    "what breaks when assumptions fail": "Ce qui casse quand les hypothèses échouent",
    "goal": "Objectif",
    "when to use it": "Quand l'utiliser",
    "steps": "Étapes",
    "menu path or shortcut if applicable": "Chemin de menu ou raccourci",
    "expected result": "Résultat attendu",
    "how to verify the output": "Comment vérifier la sortie",
    "what it measures": "Ce que cela mesure",
    "why it matters": "Pourquoi c'est important",
    "how to compute or test it": "Comment calculer ou tester",
    "how it fails": "Comment cela échoue",
    "example": "Exemple",
    "diagnostic check": "Contrôle diagnostique",
    "purpose": "But",
    "materials or conditions": "Matériaux ou conditions",
    "sensory or quality standard": "Norme sensorielle ou de qualité",
    "common failure": "Échec courant",
    "fix": "Correction",
    "period or transition": "Période ou transition",
    "what changed": "Ce qui a changé",
    "why it changed": "Pourquoi cela a changé",
    "key actors or examples": "Acteurs clés ou exemples",
    "broader context": "Contexte plus large",
    "modern relevance": "Pertinence moderne",
  },
  es: {
    "definition and intuition": "Definición e intuición",
    "why it exists": "Por qué existe",
    "problem it solves": "Problema que resuelve",
    "prerequisites": "Requisitos previos",
    "concrete example": "Ejemplo concreto",
    "relationship to neighboring concepts": "Relación con conceptos vecinos",
    "common misconception": "Malentendido común",
    "definition": "Definición",
    "intuition": "Intuición",
    "symbols and units": "Símbolos y unidades",
    "assumptions": "Supuestos",
    "when the model applies": "Cuándo aplica el modelo",
    "simple numerical example": "Ejemplo numérico simple",
    "what breaks when assumptions fail": "Qué falla cuando fallan los supuestos",
    "goal": "Objetivo",
    "when to use it": "Cuándo usarlo",
    "steps": "Pasos",
    "menu path or shortcut if applicable": "Ruta de menú o atajo",
    "expected result": "Resultado esperado",
    "how to verify the output": "Cómo verificar la salida",
    "what it measures": "Qué mide",
    "why it matters": "Por qué importa",
    "how to compute or test it": "Cómo calcularlo o probarlo",
    "how it fails": "Cómo falla",
    "example": "Ejemplo",
    "diagnostic check": "Comprobación diagnóstica",
    "purpose": "Propósito",
    "materials or conditions": "Materiales o condiciones",
    "sensory or quality standard": "Estándar sensorial o de calidad",
    "common failure": "Fallo común",
    "fix": "Corrección",
    "period or transition": "Periodo o transición",
    "what changed": "Qué cambió",
    "why it changed": "Por qué cambió",
    "key actors or examples": "Actores clave o ejemplos",
    "broader context": "Contexto más amplio",
    "modern relevance": "Relevancia moderna",
  },
  it: {
    "definition and intuition": "Definizione e intuizione",
    "why it exists": "Perché esiste",
    "problem it solves": "Problema che risolve",
    "prerequisites": "Prerequisiti",
    "concrete example": "Esempio concreto",
    "relationship to neighboring concepts": "Relazione con concetti vicini",
    "common misconception": "Fraintendimento comune",
    "definition": "Definizione",
    "intuition": "Intuizione",
    "symbols and units": "Simboli e unità",
    "assumptions": "Assunzioni",
    "when the model applies": "Quando si applica il modello",
    "simple numerical example": "Esempio numerico semplice",
    "what breaks when assumptions fail": "Cosa si rompe quando falliscono le assunzioni",
    "goal": "Obiettivo",
    "when to use it": "Quando usarlo",
    "steps": "Passaggi",
    "menu path or shortcut if applicable": "Percorso menu o scorciatoia",
    "expected result": "Risultato atteso",
    "how to verify the output": "Come verificare l'output",
    "what it measures": "Cosa misura",
    "why it matters": "Perché è importante",
    "how to compute or test it": "Come calcolarlo o testarlo",
    "how it fails": "Come fallisce",
    "example": "Esempio",
    "diagnostic check": "Controllo diagnostico",
    "purpose": "Scopo",
    "materials or conditions": "Materiali o condizioni",
    "sensory or quality standard": "Standard sensoriale o di qualità",
    "common failure": "Fallimento comune",
    "fix": "Correzione",
    "period or transition": "Periodo o transizione",
    "what changed": "Cosa è cambiato",
    "why it changed": "Perché è cambiato",
    "key actors or examples": "Attori chiave o esempi",
    "broader context": "Contesto più ampio",
    "modern relevance": "Rilevanza moderna",
  },
  pt: {
    "definition and intuition": "Definição e intuição",
    "why it exists": "Por que existe",
    "problem it solves": "Problema que resolve",
    "prerequisites": "Pré-requisitos",
    "concrete example": "Exemplo concreto",
    "relationship to neighboring concepts": "Relação com conceitos vizinhos",
    "common misconception": "Equívoco comum",
    "definition": "Definição",
    "intuition": "Intuição",
    "symbols and units": "Símbolos e unidades",
    "assumptions": "Suposições",
    "when the model applies": "Quando o modelo se aplica",
    "simple numerical example": "Exemplo numérico simples",
    "what breaks when assumptions fail": "O que quebra quando as suposições falham",
    "goal": "Objetivo",
    "when to use it": "Quando usar",
    "steps": "Etapas",
    "menu path or shortcut if applicable": "Caminho de menu ou atalho",
    "expected result": "Resultado esperado",
    "how to verify the output": "Como verificar a saída",
    "what it measures": "O que mede",
    "why it matters": "Por que importa",
    "how to compute or test it": "Como calcular ou testar",
    "how it fails": "Como falha",
    "example": "Exemplo",
    "diagnostic check": "Verificação diagnóstica",
    "purpose": "Propósito",
    "materials or conditions": "Materiais ou condições",
    "sensory or quality standard": "Padrão sensorial ou de qualidade",
    "common failure": "Falha comum",
    "fix": "Correção",
    "period or transition": "Período ou transição",
    "what changed": "O que mudou",
    "why it changed": "Por que mudou",
    "key actors or examples": "Atores-chave ou exemplos",
    "broader context": "Contexto mais amplo",
    "modern relevance": "Relevância moderna",
  },
  nl: {
    "definition and intuition": "Definitie en intuïtie",
    "why it exists": "Waarom het bestaat",
    "problem it solves": "Probleem dat het oplost",
    "prerequisites": "Voorkennis",
    "concrete example": "Concreet voorbeeld",
    "relationship to neighboring concepts": "Relatie met verwante concepten",
    "common misconception": "Veelvoorkomende misvatting",
    "definition": "Definitie",
    "intuition": "Intuïtie",
    "symbols and units": "Symbolen en eenheden",
    "assumptions": "Aannames",
    "when the model applies": "Wanneer het model geldt",
    "simple numerical example": "Eenvoudig numeriek voorbeeld",
    "what breaks when assumptions fail": "Wat misgaat wanneer aannames falen",
    "goal": "Doel",
    "when to use it": "Wanneer te gebruiken",
    "steps": "Stappen",
    "menu path or shortcut if applicable": "Menupad of sneltoets",
    "expected result": "Verwacht resultaat",
    "how to verify the output": "Hoe de uitvoer te verifiëren",
    "what it measures": "Wat het meet",
    "why it matters": "Waarom het belangrijk is",
    "how to compute or test it": "Hoe te berekenen of testen",
    "how it fails": "Hoe het faalt",
    "example": "Voorbeeld",
    "diagnostic check": "Diagnostische controle",
    "purpose": "Doel",
    "materials or conditions": "Materialen of voorwaarden",
    "sensory or quality standard": "Sensorische of kwaliteitsstandaard",
    "common failure": "Veelvoorkomende mislukking",
    "fix": "Oplossing",
    "period or transition": "Periode of overgang",
    "what changed": "Wat veranderde",
    "why it changed": "Waarom het veranderde",
    "key actors or examples": "Belangrijke actoren of voorbeelden",
    "broader context": "Bredere context",
    "modern relevance": "Moderne relevantie",
  },
  sv: {
    "definition and intuition": "Definition och intuition",
    "why it exists": "Varför det finns",
    "problem it solves": "Problemet det löser",
    "prerequisites": "Förkunskaper",
    "concrete example": "Konkret exempel",
    "relationship to neighboring concepts": "Relation till närliggande begrepp",
    "common misconception": "Vanlig missuppfattning",
    "definition": "Definition",
    "intuition": "Intuition",
    "symbols and units": "Symboler och enheter",
    "assumptions": "Antaganden",
    "when the model applies": "När modellen gäller",
    "simple numerical example": "Enkelt numeriskt exempel",
    "what breaks when assumptions fail": "Vad som går sönder när antaganden faller",
    "goal": "Mål",
    "when to use it": "När det används",
    "steps": "Steg",
    "menu path or shortcut if applicable": "Menysökväg eller kortkommando",
    "expected result": "Förväntat resultat",
    "how to verify the output": "Hur utdata verifieras",
    "what it measures": "Vad det mäter",
    "why it matters": "Varför det är viktigt",
    "how to compute or test it": "Hur man beräknar eller testar",
    "how it fails": "Hur det misslyckas",
    "example": "Exempel",
    "diagnostic check": "Diagnostisk kontroll",
    "purpose": "Syfte",
    "materials or conditions": "Material eller villkor",
    "sensory or quality standard": "Sensorisk eller kvalitetsstandard",
    "common failure": "Vanligt fel",
    "fix": "Korrigering",
    "period or transition": "Period eller övergång",
    "what changed": "Vad som förändrades",
    "why it changed": "Varför det förändrades",
    "key actors or examples": "Nyckelaktörer eller exempel",
    "broader context": "Bredare sammanhang",
    "modern relevance": "Modern relevans",
  },
  fi: {
    "definition and intuition": "Määritelmä ja intuitio",
    "why it exists": "Miksi se on olemassa",
    "problem it solves": "Ongelma, jonka se ratkaisee",
    "prerequisites": "Esitiedot",
    "concrete example": "Konkreettinen esimerkki",
    "relationship to neighboring concepts": "Suhde läheisiin käsitteisiin",
    "common misconception": "Yleinen väärinkäsitys",
    "definition": "Määritelmä",
    "intuition": "Intuitio",
    "symbols and units": "Symbolit ja yksiköt",
    "assumptions": "Oletukset",
    "when the model applies": "Milloin malli pätee",
    "simple numerical example": "Yksinkertainen numeerinen esimerkki",
    "what breaks when assumptions fail": "Mikä rikkoutuu oletusten pettäessä",
    "goal": "Tavoite",
    "when to use it": "Milloin sitä käytetään",
    "steps": "Vaiheet",
    "menu path or shortcut if applicable": "Valikkopolku tai pikanäppäin",
    "expected result": "Odotettu tulos",
    "how to verify the output": "Miten tulos varmistetaan",
    "what it measures": "Mitä se mittaa",
    "why it matters": "Miksi sillä on merkitystä",
    "how to compute or test it": "Miten se lasketaan tai testataan",
    "how it fails": "Miten se epäonnistuu",
    "example": "Esimerkki",
    "diagnostic check": "Diagnostinen tarkistus",
    "purpose": "Tarkoitus",
    "materials or conditions": "Materiaalit tai olosuhteet",
    "sensory or quality standard": "Aistinvarainen tai laatustandardi",
    "common failure": "Yleinen epäonnistuminen",
    "fix": "Korjaus",
    "period or transition": "Ajanjakso tai siirtymä",
    "what changed": "Mikä muuttui",
    "why it changed": "Miksi se muuttui",
    "key actors or examples": "Keskeiset toimijat tai esimerkit",
    "broader context": "Laajempi konteksti",
    "modern relevance": "Nykyinen merkitys",
  },
  pl: {
    "definition and intuition": "Definicja i intuicja",
    "why it exists": "Dlaczego istnieje",
    "problem it solves": "Problem, który rozwiązuje",
    "prerequisites": "Wymagania wstępne",
    "concrete example": "Konkretny przykład",
    "relationship to neighboring concepts": "Relacja z sąsiednimi pojęciami",
    "common misconception": "Częste nieporozumienie",
    "definition": "Definicja",
    "intuition": "Intuicja",
    "symbols and units": "Symbole i jednostki",
    "assumptions": "Założenia",
    "when the model applies": "Kiedy model ma zastosowanie",
    "simple numerical example": "Prosty przykład liczbowy",
    "what breaks when assumptions fail": "Co się psuje, gdy założenia zawodzą",
    "goal": "Cel",
    "when to use it": "Kiedy tego używać",
    "steps": "Kroki",
    "menu path or shortcut if applicable": "Ścieżka menu lub skrót",
    "expected result": "Oczekiwany wynik",
    "how to verify the output": "Jak zweryfikować wynik",
    "what it measures": "Co mierzy",
    "why it matters": "Dlaczego ma znaczenie",
    "how to compute or test it": "Jak obliczyć lub przetestować",
    "how it fails": "Jak zawodzi",
    "example": "Przykład",
    "diagnostic check": "Kontrola diagnostyczna",
    "purpose": "Cel",
    "materials or conditions": "Materiały lub warunki",
    "sensory or quality standard": "Standard sensoryczny lub jakościowy",
    "common failure": "Częsta awaria",
    "fix": "Poprawka",
    "period or transition": "Okres lub przejście",
    "what changed": "Co się zmieniło",
    "why it changed": "Dlaczego się zmieniło",
    "key actors or examples": "Kluczowi aktorzy lub przykłady",
    "broader context": "Szerszy kontekst",
    "modern relevance": "Współczesna istotność",
  },
  tr: {
    "definition and intuition": "Tanım ve sezgi",
    "why it exists": "Neden var",
    "problem it solves": "Çözdüğü problem",
    "prerequisites": "Ön koşullar",
    "concrete example": "Somut örnek",
    "relationship to neighboring concepts": "Yakın kavramlarla ilişkisi",
    "common misconception": "Yaygın yanlış anlama",
    "definition": "Tanım",
    "intuition": "Sezgi",
    "symbols and units": "Semboller ve birimler",
    "assumptions": "Varsayımlar",
    "when the model applies": "Modelin geçerli olduğu durumlar",
    "simple numerical example": "Basit sayısal örnek",
    "what breaks when assumptions fail": "Varsayımlar bozulunca ne bozulur",
    "goal": "Amaç",
    "when to use it": "Ne zaman kullanılır",
    "steps": "Adımlar",
    "menu path or shortcut if applicable": "Menü yolu veya kısayol",
    "expected result": "Beklenen sonuç",
    "how to verify the output": "Çıktı nasıl doğrulanır",
    "what it measures": "Neyi ölçer",
    "why it matters": "Neden önemlidir",
    "how to compute or test it": "Nasıl hesaplanır veya test edilir",
    "how it fails": "Nasıl başarısız olur",
    "example": "Örnek",
    "diagnostic check": "Tanısal kontrol",
    "purpose": "Amaç",
    "materials or conditions": "Malzemeler veya koşullar",
    "sensory or quality standard": "Duyusal veya kalite standardı",
    "common failure": "Yaygın başarısızlık",
    "fix": "Düzeltme",
    "period or transition": "Dönem veya geçiş",
    "what changed": "Ne değişti",
    "why it changed": "Neden değişti",
    "key actors or examples": "Kilit aktörler veya örnekler",
    "broader context": "Daha geniş bağlam",
    "modern relevance": "Modern ilgililik",
  },
  ru: {
    "definition and intuition": "Определение и интуиция",
    "why it exists": "Почему это существует",
    "problem it solves": "Проблема, которую это решает",
    "prerequisites": "Предварительные знания",
    "concrete example": "Конкретный пример",
    "relationship to neighboring concepts": "Связь с соседними понятиями",
    "common misconception": "Распространенное заблуждение",
    "definition": "Определение",
    "intuition": "Интуиция",
    "symbols and units": "Символы и единицы",
    "assumptions": "Предположения",
    "when the model applies": "Когда модель применима",
    "simple numerical example": "Простой числовой пример",
    "what breaks when assumptions fail": "Что ломается при нарушении предположений",
    "goal": "Цель",
    "when to use it": "Когда использовать",
    "steps": "Шаги",
    "menu path or shortcut if applicable": "Путь меню или сочетание клавиш",
    "expected result": "Ожидаемый результат",
    "how to verify the output": "Как проверить результат",
    "what it measures": "Что измеряет",
    "why it matters": "Почему это важно",
    "how to compute or test it": "Как вычислить или проверить",
    "how it fails": "Как это дает сбой",
    "example": "Пример",
    "diagnostic check": "Диагностическая проверка",
    "purpose": "Назначение",
    "materials or conditions": "Материалы или условия",
    "sensory or quality standard": "Сенсорный или качественный стандарт",
    "common failure": "Распространенный сбой",
    "fix": "Исправление",
    "period or transition": "Период или переход",
    "what changed": "Что изменилось",
    "why it changed": "Почему изменилось",
    "key actors or examples": "Ключевые участники или примеры",
    "broader context": "Более широкий контекст",
    "modern relevance": "Современная значимость",
  },
};

function getEnglishSectionTitle(section: string): string {
  return ENGLISH_SECTION_TITLES[section] ?? section
    .split(/\s+/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}

function normalizeHeadingText(text: string): string {
  return text
    .replace(/\s+#+\s*$/, "")
    .replace(/\s+/g, " ")
    .trim()
    .toLowerCase();
}

const HEADING_KEY_BY_ENGLISH_TITLE: Record<string, string> = Object.entries(
  ENGLISH_SECTION_TITLES,
).reduce<Record<string, string>>((result, [key, englishTitle]) => {
  result[normalizeHeadingText(englishTitle)] = key;
  return result;
}, {});

export function getSectionHeading(section: string, language: string): string {
  const englishTitle = getEnglishSectionTitle(section);
  if (language === "en") {
    return englishTitle;
  }

  const localizedTitle =
    LOCALIZED_SECTION_TITLES[language]?.[section] ??
    LOCALIZED_UNIT_FIELD_TITLES[language]?.[section] ??
    englishTitle;

  return `${localizedTitle} (${englishTitle})`;
}

export function buildSectionHeadingContract(
  sections: string[],
  language: string,
): string[] {
  return sections.map((section) => `## ${getSectionHeading(section, language)}`);
}

export function sectionAppearsInText(section: string, text: string): boolean {
  const englishTitle = getEnglishSectionTitle(section).toLowerCase();
  return text.toLowerCase().includes(englishTitle);
}

export function normalizeKnownMarkdownHeadings(
  markdown: string,
  language: string,
): string {
  if (language === "en") {
    return markdown;
  }

  return markdown.replace(
    /^(#{1,6}\s+)(.+?)\s*$/gm,
    (line: string, prefix: string, title: string) => {
      const normalizedTitle = normalizeHeadingText(title);
      const key = HEADING_KEY_BY_ENGLISH_TITLE[normalizedTitle];
      if (!key) {
        return line;
      }

      return `${prefix}${getSectionHeading(key, language)}`;
    },
  );
}
